image: ruby:2.3

# More about services: http://docs.gitlab.com/ee/ci/services/postgres.html
services:
  - mongo:latest
  - redis:latest

variables:
  # Configure PostGreSQL environment variables (https://hub.docker.com/_/postgres/)
  MONGO_USER: admin
  MONGO_PASSWORD: admin
  MONGO_HOST: mongo
  MONGO_PORT: "27017"

before_script:
  - cp config/mongoid-ci.yml config/mongoid.yml
  - ruby -v
  - which ruby
  - sh setup.sh
  - gem install bundler --no-ri --no-rdoc
  - bundle check || bundle install

rspec:
  script:
    - bundle exec rspec
